#
# Makefile for lclusterd
#

# 
# phony targets
#
.PHONY: all client protobufs clean

#
# make targets
#

all: build

protobuf_deps:
	@wget "https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip" -qO /tmp/protoc.zip
	@mkdir -p /tmp/protoc
	@unzip /tmp/protoc.zip -d /tmp/protoc
	@rm -f /tmp/protoc.zip
	@sudo rm -rf /usr/local/include/google/protobuf
	@sudo mkdir -p /usr/local/include/google/
	@sudo mv /tmp/protoc/include/google/protobuf /usr/local/include/google/protobuf
	@sudo mv /tmp/protoc/bin/protoc /usr/local/bin/protoc
	@rm -rf /tmp/protoc

grpc_deps:
	@echo "Obtaining gRPC..."
	@go get -u google.golang.org/grpc
	@go get -u github.com/golang/protobuf/protoc-gen-go

etcd_deps:
	@echo "Obtaining etcd..."
	@wget https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz -qO /tmp/etcd.tar.gz
	@tar -C /tmp/ -zxvf /tmp/etcd.tar.gz
	@sudo mv /tmp/etcd-v3.4.13-linux-amd64/etcd /usr/local/bin/etcd
	@sudo mv /tmp/etcd-v3.4.13-linux-amd64/etcdctl /usr/local/bin/etcdctl
	@rm -rf /tmp/etcd-v3.4.13-linux-amd64/

example_rootfs:
	@go get github.com/opencontainers/runc/libcontainer
	@docker pull ubuntu:latest
	@docker create --name ubuntu-husk ubuntu:latest
	@sudo mkdir -p /lclusterd/rootfs
	@sudo docker export ubuntu-husk | sudo tar xvfC - /lclusterd/rootfs
	@docker rm ubuntu-husk

protobufs:
	@echo "Regenerating jobpb protobuffs..."
	@protoc -I jobpb/ jobpb/jobpb.proto --go_out=plugins=grpc:jobpb

lclusterd: protobufs
	@echo "Building lclusterd..."
	@go build

client: protobufs
	@echo "Building lcluster client..."
	@go build -o lclient ./client

prep: protobuf_deps grpc_deps etcd_deps example_rootfs
	@echo "Finished setting up the infrastructure needed for lclusterd."

build: lclusterd client
	@echo "Finished building lclusterd server and client."

clean:
	@echo "Cleaning binaries..."
	@go clean
	@rm -f lclient
	@echo "Removing possible configs generated by clients..."
	@echo "Removing generated protobuff code..."
	@rm -f jobpb/jobpb.pb.go
