#
# Makefile for lclusterd
#
# NOTE: the config.go present in this directory is copied to the client
#       directory right before the `go build` step.
#

# 
# phony targets
#
.PHONY: all client regen_proto clean 

#
# make targets
#

all: regen_proto lclusterd client 

regen_proto:
	@echo "Regenerating lclusterpb from prototype..."
	@protoc -I lclusterpb/ lclusterpb/lclusterpb.proto --go_out=plugins=grpc:lclusterpb

lclusterd:
	@echo "Building lclusterd..."
	@go build

client:
	@echo "Building lcluster client..."
	@cp config.go client/config.go
	@go build -o lclusterc ./client
	@rm -f client/config.go

clean:
	@echo "Cleaning binaries..."
	@go clean
	@rm -f lclusterc
	@echo "Removing possible configs generated by clients..."
	@rm -f client/config.go
	@echo "Removing generated PB code..."
	@rm -f lclusterpb/lclusterpb.pb.go
